### ISSUE TITLE
datasest names

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/data.tnris.org#10]
i would like to go back to the idea of building the names from the inputted data.

the name field is the geography covered by the collection and the other items are pulled from the other fields.

**Comment by adambreznicky** [comment]
as discussed over the last week, there are a few too many inconsistencies related to dataset categories and what "is important" in the name. let's leave it as is for awhile as the responsibility lies on the content creators. we can revisit in the future if problems arise
