### ISSUE TITLE
Recreate TWDB Watershed Boundaries Image

### ISSUE THREAD

**Issue by christoball** [TNRIS/data.tnris.org#108]
Recreate the sample image for the twdb Watershed Boundaries.

Include simple labels, similar to the current image in use.

16:9 Ratio, 300DPI

https://data.tnris.org/collection/a3246604-801d-438e-a200-f97976a83659

**Comment by e00o** [comment]
Added four images to - M:\Website\erik_remakes_datacatalog - for WBD.

**Comment by christoball** [comment]
updated!
