### ISSUE TITLE
Remake Imagery

### ISSUE THREAD

**Issue by christoball** [TNRIS/data.tnris.org#113]
These are imagery datasets we need to remake image samples for. Will add more in comments

- [ ] CapArea-McLennan Imagery 2018, Just need a couple more higher rez examples, https://data.tnris.org/collection/22493b55-6c57-4840-aa86-d59c54b00880

SPECS
- 3000px wide
- 1687px high
- 300dpi if possible

**Comment by gmullins** [comment]
@christoball Thanks! I haven't been able to get this yet but will...

**Comment by christoball** [comment]
I also can't find higher rez versions of the SARA 2016 and it would help if you regenerated some of those. Unless you can point me to where they might be on the vault.
- [ ] SARA 2016

**Comment by gmullins** [comment]
Will any of these work for the CapArea 2018? I had previously made them but maybe you already assessed them?
M:\SM\SM Contract\2018 Projects\58017SOW0046_CapArea_McLennan_Ortho\Web_Announce\Graphics

**Comment by gmullins** [comment]
Or these for the SARA 2016? M:\SM\HPIDS\2015 Projects\580150618 Ortho\Web page\SARA_Graphics
see sara16 bunch
I don't know if these are high enough dpi. 
I'm happy to make new ones, just wanted to check first to see if these are usable.

**Comment by christoball** [comment]
@gmullins yes these all work great, the originals just weren't with all the other ones I was working from, so thanks for tracking them down.

**Comment by gmullins** [comment]
@christoball awesome!

**Comment by christoball** [comment]
images remade. resolved
