### ISSUE TITLE
brazos county imagery missing pic

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/data.tnris.org#120]
Brazos County Imagery 2017 (1d69eeb7-d3ab-48d9-8899-2d54476832ba) had 3 photos but only 2 made it back during sync. 
missing photo was: 8dece7d9-2e5d-4243-9e26-ff95dbc0e632.jpg

need to find it, upload to the collection in the admin console, then set it to be the thumbnail and re-save the collection

**Comment by mitchellryant** [comment]
upload: ../../../../data.tnris.org_names/Brazos_County_Imagery-1d69eeb7-d3ab-48d9-8899-2d54476832ba/assets/8dece7d9-2e5d-4243-9e26-ff95dbc0e632.jpg to s3://data.tnris.org/1d69eeb7-d3ab-48d9-8899-2d54476832ba/assets/8dece7d9-2e5d-4243-9e26-ff95dbc0e632.jpg
