### ISSUE TITLE
Add Roboto Condensed

### ISSUE THREAD

**Issue by christoball** [TNRIS/data.tnris.org#121]
Can we add Roboto Condensed as a font option? I'd like to try it out on some parts.

https://fonts.google.com/specimen/Roboto+Condensed

**Comment by adambreznicky** [comment]
added font family option via commit fc865e1ad6e95810426e42a2743a43526774adfb

can you provide details as to which "parts" you're looking at?

**Comment by christoball** [comment]
@adambreznicky Yes, I'd like to try out the following in Roboto Condensed:

- 'Data Catalog' Header
- All Data Card Titles
- The Main Headers on the full Entries

**Comment by jwhaney** [comment]
Data Catalog header with font-family: 'Roboto Condensed', sans-serif;

![screenshot.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b69c10b3c8a4500139e198f/125516c66e82c728ace21e0d46fb978826878dba87e6ab01e81fe086264c22703d46f9692586b279e81b78560b0e49fd49515f45f4af8c2aa4be3922984019af80330b2b9b645bf9fa9015ad00bd2a8a4a80b4bc8c49c0e93c23e7899d02.png)

**Comment by jwhaney** [comment]
Data catalog card titles/names only. Year and source not condensed.
![screenshot_1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b69c10b3c8a4500139e198f/125516c66e82c728ace21e0d46fb978826878dba87e6ab7cf51fbcd6395428792c07b7692ac7b62bee132c580c581afd4609574dfcf8817da3b73e788f0e19f1c32f0e2a92624cf5f2d75dad0ba8218c4584b3b9884cc6ed3e25e688874f2c53.png)

**Comment by jwhaney** [comment]
"The Main Headers on the full Entries"

![screenshot_2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b69c10b3c8a4500139e198f/125516c66e82c728ace21e0d46fb978826878dba87e6ab7cf61fbcd6395428792c07b7692ac7b62bee132c580c581afd4609574dfcf8817da3b73e788f0e19f1c32f0e2a92624cf5f2d75dad0ba821834584b3b9884cc6ed3523e288894e2c53.png)

**Comment by christoball** [comment]
@jwhaney no, the other text would remain the same. This would just be for header/title elements. The source, year are more supplemental

thanks, its looking good.

**Comment by jwhaney** [comment]
@christoball, did you want roboto condensed on all headers/titles?

**Comment by christoball** [comment]
@jwhaney No, for now, just those. thanks

**Comment by jwhaney** [comment]
closed with abf298b94ea29e9afd0801f4c2a0bf1d3eb36a28
