### ISSUE TITLE
Outside Entity template description width

### ISSUE THREAD

**Issue by christoball** [TNRIS/data.tnris.org#133]
I'm guessing we won't have a 'dataset citation' on the outside entity?

In that case, the description should still match the width in the other ones, leaving a gap where the citation would be.

Example of current width on TPWD entry:
https://data.tnris.org/collection/48ddc0ac-0f43-4b55-82fa-5f2d5f7fbd92

**Comment by mitchellryant** [comment]
This was discussed between @jwhaney and myself, but was forgotten to be implemented on external entity template.

**Comment by jwhaney** [comment]
resolved via commit 08074f8ee9f67199fa1867bce843dc3c7f74f4e8
