### ISSUE TITLE
add "back to catalog" button after adding item to cart

### ISSUE THREAD

**Issue by JasonKleinert** [TNRIS/data.tnris.org#138]
once an item has been added to the shopping cart, add a "back to browsing catalog" (or the like) button to the page so the user can just press that button to go back. The normal back to catalog button is in the header at this view, but it might be more helpful to provide a quick way back from there so it is more obvious.

**Comment by adambreznicky** [comment]
we should center the text/button also

**Comment by adambreznicky** [comment]
after reviewing this prospect and discussing with @JasonKleinert , we decided to hold off on this idea for now. it's a bit redundant to the current catalog grid button that's present and it removes a user's ability to continue working with the collection they're looking at.
we can return to this idea if a need arises again in the future
