### ISSUE TITLE
Header, Logo Fixes

### ISSUE THREAD

**Issue by christoball** [TNRIS/data.tnris.org#145]
Use the mockup in following comments to make changes to Catalog Header. Let me know if you have any questions or thoughts about it.

This will unify the catalog with the tnris website on launch of the catalog, which will also be adjusted to coincide with this.

**Comment by christoball** [comment]
![catalog-header-adjustments.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599de1581827cf2b06d2e400/125516c66e82c728ace21e0d46eb958e228e8caec2e1ba42a058e2d928422d663a10ae2e7e91f06af3006b1300051bff054a5556f9aa882aa1bf6f77de0d0cbcd9645f75ce6b14adba8a1aed13a632c91edbe2e3d7158abd7f37ed998e48341f001d8bfb5d32a19149cd59f659ac.jpg)

**Comment by christoball** [comment]
The white tnris logo is available as an svg here:
http://www.tnris.org/static/images/tnris_logo.svg

**Comment by jwhaney** [comment]
commits 773cd7984fd1f1db1a2aa712a7421985a6030be8, 59229e456980ebfeaae2c3a64e4f16ec24e199e0

**Comment by jwhaney** [comment]
reference commit 59229e456980ebfeaae2c3a64e4f16ec24e199e0
