### ISSUE TITLE
Download Template: Zip File

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/data.tnris.org#151]
Can the href be changed to just Download?

<img width="740" alt="Screen Shot 2019-03-14 at 11 22 44 AM" src="https://user-images.githubusercontent.com/8459928/54373746-d44fc580-464b-11e9-97c1-c9735e8781d4.png">

**Comment by adambreznicky** [comment]
resolved 69871ec4e0d2ab7acb0c1d4a42aa2a4724ea3ff4
