### ISSUE TITLE
Contact Forms

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/data.tnris.org#152]
Can you change the email subjects to remove data.tnris.org?

Dataset Inquiry
Dataset Order
Historic Order
Historic Inquiry

If the collection name(s) could be added that would be cool, but not as deal killer.

**Comment by adambreznicky** [comment]
contact app updated via commit 7c271515216aa2acca05a65b5a6404763b684297

emails are sent under only 2 identifiable types: contact inquiry and data orders. there is not differentiation between historic vs non-historic. 
contact app is also setup such that the subject is pre-defined within a default config file for each 'type' of email opposed to dynamic based on the content of the inquiry. 
also, orders can have any number of datasets associated so labeling a slew of datasets in the subject of an email isn't very practical.
all this in consideration, all emails will be subjected as either "Dataset Inquiry" or "Dataset Order". "data.tnris.org - " has been removed
