### ISSUE TITLE
TNRIS Logo too small, other header fix

### ISSUE THREAD

**Issue by christoball** [TNRIS/data.tnris.org#155]
The TNRIS logo is too small in the header.

In my mockup I specified 75px wide for the logo. It looks like it's set to width: auto, based on how heigh the mdc-top-app-bar_ is.

This will not match with the current website and just looks too small.

Setting the header at 30px makes the logo 70px wide. I think this is fine if we want the top bar to take up less space but any smaller doesn't look good.

- Also, please make the 'letter-spacing: 0px' for the 'Division of the Texas Water Development Board'

**Comment by christoball** [comment]
Here is the header mockup I submitted with the last issue.

![header.jpeg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599de1581827cf2b06d2e400/125516c66e82c728ace21e0d46e0919b278791ebc3abaf51ab57f5973d047d317c07f27a27dce07fbb432c0057564ead490e5a45fef18c79b4aa2e32db025fb28c341521842f1bbeb98b15be04bf238b4e87b1b9884dc5eb2f68.jpeg)

**Comment by jwhaney** [comment]
i'm aware of the mockup you provided. i looked at increasing the blue header to allow for the larger tnris logo you specified and we agreed that it was too big. currently, on tnris.org the logo is not in the blue header, it's in the black portion underneath which provides more room for a larger logo. i don't mind increasing it a little for a bigger logo but it might not be 70px wide.

just an FYI, if you look at the height comparison below between tnris.org's blue header and the current data.tnris.org blue header, tnris.org is actually 1px smaller. so, it doesn't quite make sense to me when you say that the header being any smaller doesn't look good or that This will not match with the current website and just looks too small. the height of the blue bar is almost identical to tnris.org.

![Screenshot from 2019-03-19 11-43-36](https://user-images.githubusercontent.com/13525011/54624890-42293200-4a3c-11e9-9766-13bb6a07cbdb.png)

i will make the letter-spacing change you specified.

**Comment by jwhaney** [comment]
clarification with @christoball on matching data.tnris.org blue header with the NEW tnris.org design make sense.

changes made include blue header to height of 35px, logo to 30px height with 4px padding-top, 0px letter-spacing for twdb text, and baseline for tnris and twdb text to bottom of image.

**Comment by jwhaney** [comment]
resolved with commit 9ab892ce0845e516ee843637aa7e1fbb41752817
