### ISSUE TITLE
inconsistent naip search

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/data.tnris.org#158]
as per feedback--
Just noticing when I search for the following on data.tnris.org I get no results.
2010 naip
naip 2010
2012 naip
naip 2012

While this does bring up the dataset successfully.
naip 2004
2004 naip
naip 2006
2006 naip

@adambreznicky was able to reproduce this. @jasonkleinert got different, but still inconsistent search term, behavior. something to look into in the future.

**Comment by JasonKleinert** [comment]
closing because this bug can't be reproduced. Will reopen if it comes up again.
