### ISSUE TITLE
search on safari desktop

### ISSUE THREAD

**Issue by jwhaney** [TNRIS/data.tnris.org#16]
apple/safari likes to hijack the design of search boxes...

**Comment by adambreznicky** [comment]
this needs to be reviewed after @JasonKleinert completes the search bar move to the header center

**Comment by jwhaney** [comment]
I have tested the new search using browserstack and i believe this is now complete with commit 72ff6df36593c324f87fb22ee3dcd5eb174f7994, as well as the other work @JasonKleinert completed. safari does not hijack the design of the new mdc/downshift search anymore.

yay Jason!
