### ISSUE TITLE
Load Time

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/data.tnris.org#161]
Can the load time be decreased? 15-20 seconds is too long for the page to load. 

Tested at my house using laptop and ipad.

**Comment by adambreznicky** [comment]
the load functionality would need a deep dive in order to reconfigure the way it works. this is a significant and fundamental change to the app. i'm swapping out the v1 TODO label for a future label since this is a major enhancement and needs to be looked at later down the line. we can glance at it now but i cannot imagine this is the type of thing that can be fixed in the next few days.

**Comment by mitchellryant** [comment]
Does load time decrease if categories are changed to everything but Historic?

<img width="252" alt="Screen Shot 2019-03-25 at 1 52 46 PM" src="https://user-images.githubusercontent.com/8459928/54946176-80739500-4f05-11e9-9299-bee235df227e.png">

**Comment by adambreznicky** [comment]
no, that shouldn't make any difference. load time is based on the retrieval of all the collections from the api, not their display. i think the best luck at an efficient fix would be upping the ec2 and rds cpu hardware or 
(possibly) the number of instances of the app container

**Comment by adambreznicky** [comment]
updated collection views to be materialized. this has cut load time down to 3-9 second range.

will need to continue to materialize views and tune dbase for performance
also, need to set up materialized view refresh triggers

**Comment by adambreznicky** [comment]
to do:
- [ ] materialize other views (ChC & CCR done)
- [ ] write materialized views refresh triggers (every 24 hours)
- [ ] write routines to index all tables on a schedule
- [ ] write routine to update carto CSV in s3

**Comment by adambreznicky** [comment]
outside_entity_services lambda should needs to be updated and deployed to run a refresh on the ccr materialized view after updating the table. 
wiring a trigger to this table is waaaaay too cumbersome as it would fire hundreds of times. lambda should just run a single refresh after all table updates complete

**Comment by adambreznicky** [comment]
wrote materialized view refresh into lambda function after experimenting with triggers and seeing terrible admin console performance
triggering on table edits runs the refresh after every admin console edit and save. this caused every save to extend time to include the refresh, ultimately leading to admin console edits timing out (nginx has max time of 30 sec).
lambda created in commit f7dc8cfc6379cb4004f9c70388ef1e19bd09cb69

**Comment by adambreznicky** [comment]
resource_management view is used by download map (RemView; /resources api endpoint) and should be materialized

**Comment by adambreznicky** [comment]
updated areas_view csv to drop into nested carto-resources folder in s3 rather than the bucket base
