### ISSUE TITLE
Sharing Subject

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/data.tnris.org#164]
Please change Sharing Subject. Remove Holodock and second data.

Maybe: Check out this TNRIS Data Catalog Collection!

<img width="478" alt="Screen Shot 2019-03-25 at 1 47 37 PM" src="https://user-images.githubusercontent.com/8459928/54945805-ab111e00-4f04-11e9-800d-991f2eb9f73f.png">
<img width="552" alt="Screen Shot 2019-03-25 at 1 48 18 PM" src="https://user-images.githubusercontent.com/8459928/54945808-acdae180-4f04-11e9-9e08-d5c687527a25.png">

**Comment by jwhaney** [comment]
resolved with commit 493b2a134f394eb916ee65c4f819fdf1fa3f76ad

![image](https://user-images.githubusercontent.com/13525011/54998205-8c119b00-4f9b-11e9-9389-ccbf2c317985.png)

**Comment by jwhaney** [comment]
updated to new app title dataHub with commits b233fc5e2e92f11f9090b376e3f1b2b7c30e0973

![image](https://user-images.githubusercontent.com/13525011/55031160-f77b5d00-4fdb-11e9-907c-c45492eab1e5.png)
