### ISSUE TITLE
Left align on data entries

### ISSUE THREAD

**Issue by christoball** [TNRIS/data.tnris.org#165]
Can you align the titles and metadata on entries to the same left line?

The metadata text doesn't need to be left aligned, just everything shifted over so the divider line is left aligned.

![image](https://user-images.githubusercontent.com/1877550/55032278-8f7a4600-4fde-11e9-889c-9a7110c001b4.png)

**Comment by jwhaney** [comment]
resolved with b1b64ddc46ce3a9b22227e7960d46656bd4f51c9
