### ISSUE TITLE
change app title to bactrian camel case

### ISSUE THREAD

**Issue by jwhaney** [TNRIS/data.tnris.org#166]
"DataHub"

**Comment by jwhaney** [comment]
or maybe this? i like this...

![dataHub](https://user-images.githubusercontent.com/13525011/55087678-77570500-5078-11e9-947a-83ab7ea86f2b.png)

**Comment by adambreznicky** [comment]
title should be updated in the html template head <title> tag also. right now it says "TNRIS Data", boooooooo

**Comment by adambreznicky** [comment]
resolved 0e2c6fd6404ed3916014aba39cd66b8636f29742
also updated favicon
