### ISSUE TITLE
Change text color on Order Form (Dark Mode 

### ISSUE THREAD

**Issue by csidenblad** [TNRIS/data.tnris.org#167]
The text for the drop downs on the order form are not legible. (i.e. state and industry) White text on white background. Can we change text color to something darker? 
![image](https://user-images.githubusercontent.com/23489372/55104195-e98b1200-5097-11e9-93ad-0fd2e7b73166.png)

**Comment by csidenblad** [comment]
Can we also lighten the text for ‘no file chosen’ from black while in dark mode?

**Comment by JasonKleinert** [comment]
closed with commit fe506d34b1242d11f42384a5a1e659000cd754a2
