### ISSUE TITLE
Order Form Changes 

### ISSUE THREAD

**Issue by csidenblad** [TNRIS/data.tnris.org#168]
- [ ] remove  "TNRIS will call for credit card number? " within Payment method.

**Comment by adambreznicky** [comment]
you think it should go away completely or just be changed?
i do see the benefit of it being there insofar as users who choose a credit card payment method will by default expect to enter it in the form but we don't work that way.

maybe we should just take it out of the parenthesis and put it below as a smaller, lighter caption like the 'Fedex' delivery option does for it's note? (see pic)

![Screenshot from 2019-03-29 07-54-39](https://user-images.githubusercontent.com/5650145/55233929-ef980480-51f7-11e9-9d2e-0a905724f945.png)

**Comment by adambreznicky** [comment]
resolved 5cb24ac7a02fee076245178cb53f3176f40c4f92
