### ISSUE TITLE
TLS

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/data.tnris.org#172]
Scanning your site.   Noticed you running TLSv1   This needs to be disabled.  You should be using TLSv1.1 and TLSv1.2

**Comment by adambreznicky** [comment]
in aws, brought up the load balancer. clicked the Listeners tab. for https protocol, under the Cipher column, chose to 'Change'. Changed to ELBSecurityPolicy-TLS-1-1-2017-01 to permit only TLSv1.1 and TLSv1.2, not TLSv1.0
