### ISSUE TITLE
Load Screen

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/data.tnris.org#174]
Per Richard.

> Don’t forget to remove the “loading” bar from the DataHub before launch!

@JasonKleinert showed me this https://www.react-spinners.com/

I like the Grid loader.

**Comment by mitchellryant** [comment]
[state_animated.svg.zip](https://github.com/TNRIS/data.tnris.org/files/3019729/state_animated.svg.zip)

**Comment by JasonKleinert** [comment]
Changed to grid loader per your request @mitchellryant. closed with commit fe506d34b1242d11f42384a5a1e659000cd754a2
