### ISSUE TITLE
Add Maps

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/data.tnris.org#176]
Per request for our leader, maps will be added to DataHub.
At this time only adding Standard Map series maintained by @e00o.

Backend: new table to hold info. Relates to datasets.
Frontend: new template.

There is more

**Comment by adambreznicky** [comment]
![IMG_20190424_070858](https://user-images.githubusercontent.com/5650145/56658426-3bf02c00-6660-11e9-8f8f-8abf5cb69c19.jpg)

**Comment by adambreznicky** [comment]
![IMG_20190424_102408](https://user-images.githubusercontent.com/5650145/56672339-e9246d80-667b-11e9-954d-213e048add73.jpg)

**Comment by adambreznicky** [comment]
resolved bf2f5ffd834b4e3c8450347e86a8b31a80813b27
tables created with domains and relationships. api endpoint created to access from frontend (last step outlined above) when the new tnris.org project is underway. all set up to start filling up the database

**Comment by e00o** [comment]
Word. Let's party.
