### ISSUE TITLE
No Coverage Map for Harris County Flood Control 2001

### ISSUE THREAD

**Issue by csidenblad** [TNRIS/data.tnris.org#178]
This dataset does not have a coverage map. Please update. @ThorTheDestroyer @mitchellryant

**Comment by ThorTheDestroyer** [comment]
@mitchellryant I'll make the index shape.

**Comment by csidenblad** [comment]
Dev's had me check again and looks like coverage is there. Just wasn't loading when I looked the first time. @ThorTheDestroyer

**Comment by JasonKleinert** [comment]
Verified this one has a coverage map.Issue was created because of our persistent in network cdn error, so it appeared that there was no map.
