### ISSUE TITLE
Make 'filter by geography' tip on map default to open on desktop

### ISSUE THREAD

**Issue by christoball** [TNRIS/data.tnris.org#181]
Instead of hiding the tutorial info by default, have it open on desktop.

Default to hidden for Mobile.

**Comment by jwhaney** [comment]
resolved with 392352e182472eb05850deb7f539d957c6ed4fd6

**Comment by jwhaney** [comment]
also, for mobile - 6834f37e0c0b3efd72559172d129499976027a84
