### ISSUE TITLE
Map Weirdness

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/data.tnris.org#186]
Map tiles for area around Palestine does not show. Data is in S3, Resources are in DB. Missing tiles jump around to other parts of dataset but always Palestine.

Data was recently updates and resources re-run.

<img width="899" alt="Screen Shot 2019-05-03 at 2 17 12 PM 2" src="https://user-images.githubusercontent.com/8459928/57160413-576cdc80-6dae-11e9-9ec0-2ee9d6d1cd79.png">

**Comment by adambreznicky** [comment]
@mitchellryant dataset name or uuid??
is this occuring only for this dataset, or all datasets that have resources for the area?

**Comment by mitchellryant** [comment]
I have seen it in 2 collection so far
Neches and Upper Coast

**Comment by adambreznicky** [comment]
api pagination was randomly duplicating records between response chunks. updated api to return ordered list so that response is consistent and doesn't duplicate

resolved d4b8732a2cecbcb14c7e7f19ceb7de3641542c25
