### ISSUE TITLE
Unable to upload zip file on Order Form 

### ISSUE THREAD

**Issue by csidenblad** [TNRIS/data.tnris.org#187]
@adambreznicky @jwhaney @mitchellryant @JasonKleinert 
Order form will not upload zip file when requesting partial coverage. 
![image](https://user-images.githubusercontent.com/23489372/57483402-63541500-726c-11e9-9bb9-8ca5631fc25c.png)
![image](https://user-images.githubusercontent.com/23489372/57483416-6f3fd700-726c-11e9-9c24-a78a82f7ae7b.png)

**Comment by adambreznicky** [comment]
tested and contact app worked locally, but not deployed.
i just rebuilt my local and redeployed it. seems to be working now.
i can only assume contact app must have been redeployed with bad secrets.
