### ISSUE TITLE
Geocoder Extent returning non-intersecting collections 

### ISSUE THREAD

**Issue by csidenblad** [TNRIS/data.tnris.org#22]
When using 'Search by location bbox' several collections were returned that did not intersect with the extent of the AOI
![image](https://user-images.githubusercontent.com/23489372/132700970-e6cd6652-20e6-4a63-9fd5-e9f1512efc3b.png)

Good example would be Lake Athens. https://betadata.tnris.org/?map=true&pg=1&inc=24&geo=-95.7856702%2C32.1970145%2C-95.7190112%2C32.2335574&category=Lidar#7/31.262/-97.031
Location name search: 'Lake Athens' and filtered by category 'Lidar', returned 7 collections 5 of which do not interest the extent.

**Comment by ctrepka** [comment]
@csidenblad yes, this is because the intersect query is run on the bounding box of the footprint geometry in the django backend. When developing we decided to use the in_bbox intersect query to produce snappier geosearches... admittedly a pretty big trade-off.

**Comment by ctrepka** [comment]
I'll look into alternative geosearch queries, hopefully there is a simple and quick solution. I do believe this is a problem worth addressing.

**Comment by ctrepka** [comment]
confirmed today that this is possible and should be fast enough not to hinder ux. 

can use the default filter behavior in django like ?the_geom__intersects(${geometry_as_wkt}). [this is for personal reference when I tackle the issue later].

The URL pattern on betadata.tnris.org will remain the same, only the backend query to django will be altered.

I will swap out the filtering mechanism next week to resolve this issue.

**Comment by ctrepka** [comment]
Issue resolved, closing
