### ISSUE TITLE
Zip files not included in orders

### ISSUE THREAD

**Issue by csidenblad** [TNRIS/data.tnris.org#26]
Orders coming in from datahub do not include uploaded zip file, instead they are listed as undefined. 
![image](https://user-images.githubusercontent.com/23489372/138321563-b4be11ab-c085-477b-a21e-67f30baa2953.png)

**Comment by ghost** [comment]
@csidenblad did they upload a file?
![image](https://user-images.githubusercontent.com/8459928/138483573-517d4df9-3043-48de-9780-af1b4cc9c91c.png)
