### ISSUE TITLE
image and thumbnail updates

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/data.tnris.org#26]
- [ ] images should be standardized in size/resolution
- [ ] THUMBNAILS: @gmullins suggested using statewide graphics for statewide ortho datesets (like naip and top) and zoomed in graphics for regional ortho datasets. great idea!
- [ ] all outside entities need new graphics. either quality logos acquired directly from those agencies or custom, consistent ones created in house

**Comment by adambreznicky** [comment]
image standardization is the highest priority of the 3. next priority is the new graphics for the outside entity. third would be changing the graphics themselves.

collection card thumbnails are ratio 16:9 and this ratio works well within the collection detail page layout and the image carousel. therefore, the ***standard for all images (including thumbnails) is a 16:9 ratio, 1955x1100 pixels***. this size should yield a quality looking jpg photo for thumbnails and for carousel viewing while not disrupting performance

**Comment by jwhaney** [comment]
all of the small square thumbnail images from public collections have been deleted. 

note: there are some non-public collections that still have the small thumbnails. these collections will likely be deleted at a later time.

**Comment by adambreznicky** [comment]
this will be a running task for @christoball @gmullins @ThorTheDestroyer related to all datasets. the bulk standardization has been compeleted by @christoball already (which is what this issue was really about) so i'm closing it
