### ISSUE TITLE
BBox into Collection Cards

### ISSUE THREAD

**Issue by ghost** [TNRIS/data.tnris.org#27]
Could we investigate passing the bbox from the address or drawn search area into the collection card download map. So download map zooms that area.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/8459928/138945780-cb8a84ab-5563-43e4-9ef5-b345637b5306.png)

**Comment by ctrepka** [comment]
I know I just demoed this yesterday, but I am wondering if it would be clearer to have a checkbox in the map pane that says something like "Search as I move the map" like in AirBnb rather than the bbox draw functionality.

As for the zooming when hovering on cards, I am thinking I will make this a right click functionality with a popup menu where options include
1. copy collection link
2. view collection
3. zoom to collection extent
4. filter by collection extent

By default, hovering over a collection would not zoom the map automatically, only if right-clicked and "zoom to collection extent" is selected.

**Comment by ghost** [comment]
The "user feedback" has 2 question, and should be split into 2 issues (i think).

1. clear up draw a box -  Not clear how to draw the box, clicking on opposite corners is a shot in the dark, box just appears (not drawn as you go), map zooms out to extent of datasets on hover (keeps jumping around despite me being already zoomed in where I want).
2.  drawn bound box in collection card  - Box DISAPPEARS when dataset is selected AND MAP ZOOMS AWAY AGAIN.

I would like to be clear on what im asking for this issue, and i think he is asking in the second part of his "feedback". 

When you draw Draw search boundary. the map zoom there.  the URL changes https://data.tnris.org/?inc=24&map=true&pg=1&geo=-98.84205500300365%2C33.301185219913265%2C-98.65327992896835%2C33.413810550122946#8.79/33.0602/-98.5466. 
 
![27-SetBox](https://user-images.githubusercontent.com/8459928/139267342-a88409d0-1cd4-4838-ba8b-18349e39cd83.png)

I am assuming this portion of the URL is the UL and LR of the drawn box -98.84205500300365%2C33.301185219913265%2C-98.65327992896835%2C33.413810550122946 

But when you open a Collection, https://data.tnris.org/collection?c=a3c04828-1036-481b-b1e0-bb456c3cbcf4#4.84/31.32/-100.12

![27-CollectionCard](https://user-images.githubusercontent.com/8459928/139268338-9d3cab84-907a-4f10-ac52-e71d54fe16fc.png)

I am assuming this portion of the URL 4.84/31.32/-100.12 controls the map extent.

Would it be possible, if the user draws a box to pass (and zoom) the extent of the box into the collection card.

**Comment by ghost** [comment]
I hope this helps!

**Comment by ctrepka** [comment]
Addressed a few issues which I think were mentioned in this ticket

1. Reduce zoom / pan animations - too much motion
2. Reduce zoom / pan animations - automatic panning overrides agency of end-user
3. Maintain search boundary in collection metadata view - search boundary was previously removed and lost the context of the search
4. Maintain zoom from catalog in collection metadata view - zooming to extent of collection overrides agency of end-user

fixes for 1-3 were implemented. A fix for issue 4 may be committed soon, but I'd like to receive more feedback on this issue before changing the application behavior for this particular point
