### ISSUE TITLE
Theme color updates

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/data.tnris.org#29]
All theme colors need to be reviewed and updated across all components since major layout changes have been implemented. some don't properly contrast anymore.

**Comment by jwhaney** [comment]
please refer to issues #48 and #49. will still need to review/QA QC the default (white) and dark themes though.

**Comment by adambreznicky** [comment]
themes removed and light/dark cleaned up via commit 0bce31f0a179172b713ab7cb0de4b8250dd87628
