### ISSUE TITLE
External Entity Cards

### ISSUE THREAD

**Issue by ghost** [TNRIS/data.tnris.org#29]
The External Entity Cards have no resources to be downloaded or ordered. Could those Tabs not show on cards?

https://data.tnris.org/?inc=24&map=false&pg=1&availability=External+Link#5.5/31.33/-99.341
![image](https://user-images.githubusercontent.com/8459928/139271929-835f24b4-9d75-413b-abd6-4a208ac0f98a.png)

![image](https://user-images.githubusercontent.com/8459928/139272497-d2bb4aef-931f-42dc-9357-9928f4efc558.png)

**Comment by ghost** [comment]
More Detail.
This guy placed an order from the Texas Dept. of Transportation
![image](https://user-images.githubusercontent.com/8459928/139304154-e2c5dbcd-d7b3-46b4-9899-2e862bc23736.png)

![image](https://user-images.githubusercontent.com/8459928/139305977-f27d3da8-b876-4d9a-b241-ab40e09fb750.png)

**Comment by ctrepka** [comment]
Fixed by https://github.com/TNRIS/data.tnris.org/commit/ec05a4874c60f8dfa6f612b065a8f38a32684f46
