### ISSUE TITLE
Acquisition Date included for Historic Imagery Requests 

### ISSUE THREAD

**Issue by csidenblad** [TNRIS/data.tnris.org#33]
Please include 'Acquisition Date' for all dataset requests submitted through DataHub. 
Please include the 'From Date' within LORE as the 'Acquisition Date' for each Historical Request. This was how the orders would come in prior to the switch to V2. 

 V1 Submitted Ticket 
![image](https://user-images.githubusercontent.com/23489372/144890693-af331f3b-c731-48a3-bfa0-ed997bdb26b5.png)

VS. Current V2 Tickets 
![image](https://user-images.githubusercontent.com/23489372/144890899-8ea93374-0f54-4bfa-975b-4445d86c951c.png)

**Comment by ctrepka** [comment]
Added in https://github.com/TNRIS/data.tnris.org/commit/8325a9c7d37ce5b111e19c15958e94751f6a7720
