### ISSUE TITLE
tool drawer scroll

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/data.tnris.org#36]
scrolling behavior needs to be fixed. sidebar content should scroll only within the drawer itself and to the length of its' contents. scrolling down the catalog cards, the tool drawer content should be sticky and always present

**Comment by jwhaney** [comment]
i think the tool drawer currently functions as you intended @adambreznicky . i believe you fixed this in a previous commit. however, i noticed that the mdc-list-group .scroll div was not the full width of the tool drawer so i increased it via commit 651bacd57ad1d3d080ea7e39fb2f64d6f92b4575. take a look when you get a chance and maybe we can close this issue.

thanks.

**Comment by jwhaney** [comment]
![final2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b69c10b3c8a4500139e198f/125516c66e82c728ace21e0d46ee9d94228ed1ebc3abaf51ab57f5973d047d317c07f27a27dce07fbb432c0057564ead490e5a45fef18c79b4aa2e32db025fb28c341521842f1bbeb98515be04be288a4785b7b4894bc2eb2f68.png)

**Comment by adambreznicky** [comment]
seems to be working as expected now. although, on mobile, scrolling propagates below into the catalog when the tool drawer hits the bottom. not really a "problem" but noteworthy if we want to alter that behavior

**Comment by jwhaney** [comment]
mobile tool drawer scroll issue should be resolved withcommit 14b0df9c7ad9653e4dc202626303e1e0a99b8949, however, desktop needs some additional tweaks still.

**Comment by jwhaney** [comment]
resolved with issue d719d977d0486304ff133d9677777055313e7394
