### ISSUE TITLE
Add 'Buildings' category to collections/filtering

### ISSUE THREAD

**Issue by csidenblad** [TNRIS/data.tnris.org#36]
Hey @ctrepka . We are close to uploading the 3dbuilding datasets as assets to their corresponding lidar collections. Management would like an easy way to identify these collections within the DataHub. One suggestion made was to add another category within the API in the Lookup/Relate Associations. 
![image](https://user-images.githubusercontent.com/23489372/153283525-1827f119-5475-4ad3-8ddd-fd46f6b9381c.png)
We'd like this option as it would make it visible to the downloader via the collections tiles. 
![image](https://user-images.githubusercontent.com/23489372/153283822-91d80add-6871-4c9d-b8e8-51167c34f904.png)

Figured this might be the simplest way to make these data easy to find. 
Let me know your thoughts and suggestions. 
CS

**Comment by ghost** [comment]
@csidenblad

This is done with out a GitHub Request.
![image](https://user-images.githubusercontent.com/8459928/153286628-02fee253-2cbf-487f-888d-898dbdc348f4.png)

**Comment by csidenblad** [comment]
@mitchellryant I don't have access to the Category Types. Can you please add it for me? I only have access to Collection Footprints and Dataset Collections tables.

**Comment by ghost** [comment]
Yes i can.

But are **Buildings** a **Category** or are they a derivative product of the Lidar they were created from?

**Comment by csidenblad** [comment]
Thank you @mitchellryant 

they are a derivative product of the lidar but FR and GM would like to have some sort of mention of the buildings on the data cards. The only info currently on the data cards are collection name, date, category, and availability.

**Comment by ghost** [comment]
The downloads will be here.
![image](https://user-images.githubusercontent.com/8459928/153290677-2c6f5184-bd0f-4694-863a-bb0b6d67037e.png)
Text can be added to the Description that building are available, here.
Like  **Buildings created from this Lidar collection available in Supplemental Downloads.**
![image](https://user-images.githubusercontent.com/8459928/153290928-25c80cea-1289-4626-8d7c-11d7359a567b.png)
Part of what was created with data.tnris.org and the API was a humongous look and feel, with a removed of special cases.
