### ISSUE TITLE
Add New Data to Catalog

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/data.tnris.org#40]
all new datasets which have come in since this past fall need to be added to the catalog. This includes everything going back to at least CapArea McClennan imagery. 

also, the google texas imagery service should be added as well

**Comment by mitchellryant** [comment]
StratMap Smith-ETX 2018 6in NC\CIR Orthoimagery
StratMap CapArea-McLennan 2018 6in 12in NC\CIR Orthoimagery
StratMap 2018 50cm Crockett County Lidar
USGS 2016 70cm Neches River Basin Lidar
USGS 2014 70cm Archer Jack Lidar
USGS 2016 Middle Brazos and Lake Whitney 70cm Lidar
USGS 2017 70cm Amistad National Recreation Area Lidar
StratMap 2017 Jefferson 50cm & Liberty/Chambers 35cm Lidar
StratMap 2017 50cm Central Texas Lidar

**Comment by mitchellryant** [comment]
Data descriptions tied to https://github.com/TNRIS/data.tnris.org/issues/4
