### ISSUE TITLE
Lee, Leon, Madison, & Milam Counties Lidar - missing downloads

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/data.tnris.org#44]
the database had record to breaklines, supplemental report, and tile index zipfiles being available for the Lee, Leon, Madison, & Milam Counties Lidar 2010 dataset but they don't exist in s3. therefore, their existence was removed from the database. please verify they are not supposed to exist and if they do need to be available, use the admin console to upload them so they are available

**Comment by mitchellryant** [comment]
when i try to upload the zip files, it immediately errors out.

This site can’t be reached The connection was reset.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_RESET

**Comment by mitchellryant** [comment]
breakline and reports added.
