### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/data.tnris.org#48]
We are going with 2 themes. Please comment out or remove themes but default and dark theme. @christoball will provide design for dark theme.

**Comment by jwhaney** [comment]
this issue incorporates the change to TNRIS blue as default theme as well.

**Comment by jwhaney** [comment]
https://camo.githubusercontent.com/a451a4bb12289e4a142526145796e883689a9525/68747470733a2f2f776166666c65696f2d6469726563742d75706c6f6164732d70726f64756374696f6e2e73332e616d617a6f6e6177732e636f6d2f75706c6f6164732f3539396465313538313832376366326230366432653430302f31323535313663363665383263373238616365323165306434366563393538653232636638306138396265386233346361333130663539613364353433653365323730316234363933636337663333616230343837653032316234643434626534343062356534356662663064613263663265373362323138323535306265636439336235613735633433353134666561613965306466643530653437346434313264636663653963383565636166613363323265643861386134623339313930313138386566363539333361383938353938352e6a7067

**Comment by jwhaney** [comment]
![tnris_blue_color_code.jpeg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b69c10b3c8a4500139e198f/125516c66e82c728ace21e0d46fc9a882a91bcab83fcba7ca752fc9b3b79247c2d01e1673295f127b54778154d555ca912595e43f5aa8e7ff7b16d78835c0ae587685e76ce3843bea4905dee5fee7fd616cfe3fe9846d2e9342fe68e8b48361a041c81f95d3da38b06.jpeg)

**Comment by jwhaney** [comment]
![collection_details_img.jpeg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b69c10b3c8a4500139e198f/125516c66e82c728ace21e0d46eb9b962f8780bd86e6b17ca058e495204a344c2009a4693cc7f33ab0487e021b4d44be440b5e45fbf0da2cf2e73b2182550becd93b5a75c43514feaa9e0dfd50e474d412dcfce9c85ecafa3c2ced8a8a4b391601198cff5f3ca1915985.jpeg)

**Comment by jwhaney** [comment]
added the blue to default theme with commit e13d2ae5f30a20afe997dc29d0969a215ef68cdd. still need to comment out/remove all themes except dark and light/default.

**Comment by jwhaney** [comment]
full theme list commented out in ThemeChooser.jsx component; new list with only light and dark. commit 01e6977c468eae03230f05897dc02075a000e278
