### ISSUE TITLE
Add S3 URI and Site for Download Template.

### ISSUE THREAD

**Issue by ghost** [TNRIS/data.tnris.org#51]
Im looking to add the S3 location to the [data.tnris.org](https://data.tnris.org/collection?c=a6a703ba-df8b-4d1b-8d4c-ece8ae786505#4.89/31.32/-100.12) download template.  

S3 site ex. - `https://tnris-data-warehouse.s3.us-east-1.amazonaws.com/index.html?prefix=LCD/collection/`
S3 URI ex. - `s3://tnris-data-warehouse/LCD/collection/`
S3 Key ex - `stratmap-2010-1m-lee-leon-madison-milam/`

To do this for download collection i think we will need to field or table to the DB, to hold the key (dir) locations.  Unfortunately the key and collection names are the same and you can not build the URL|URI from existing information within the collection. The key location will need to be manually added by @csidenblad or myself. 

i was think we could add the input location to the console here:
![image](https://user-images.githubusercontent.com/8459928/201117746-7d7dc7e6-b87f-4512-950e-147e2487ef5d.png)

Maybe adding it to the download template here, under Metadata. Maybe collapsible too. 
![image](https://user-images.githubusercontent.com/8459928/201119461-238efaca-baf3-404a-9eb8-ecdb03c80d46.png)

As also, Im open to improvements on this rough idea.

**Comment by ghost** [comment]
S3 Key for download collections has been updated!

**Comment by L-Har** [comment]
This is done now.
