### ISSUE TITLE
naip 2006 zipfiles outside resources folder in s3

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/data.tnris.org#54]
a huge slue (over 13,000) naip 2006 zipfiles are outside/adjacent to the resources folder in s3. resource form in admin console ran without errors to add all the downloads for this dataset but didn't include those outside the resources folder. they need to be moved into the resources folder for this collection so that i can re-run the resource form and update the downloads.

collection id: df508fc6-c18a-4044-b0f7-35f3b9f64c02

**Comment by mitchellryant** [comment]
13,006 to be exact

**Comment by adambreznicky** [comment]
Just a notice for documentation purposes in case someone is curious about this new error: since all contents of the bucket for this collection were temporarily deleted, the images ("assets") are causing 404 errors on the collection card and in the details page.

**Comment by adambreznicky** [comment]
resource form re-run succesfully. 13,005 total zipfiles.
