### ISSUE TITLE
contact busted?

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/data.tnris.org#56]
contact form needs retesting. it is reported to be giving a 403 Forbidden error in production.

**Comment by adambreznicky** [comment]
investigated and it seems the app the required 2 contact env variables were not present in the set-env-secrets.sh file when it was last deployed. setting these and then redeploying should fix it. i'll leave the issue open until this happens and it is tested successfully

**Comment by jwhaney** [comment]
looks like contact tnris form works after latest deployment.
![contact_tnris.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b69c10b3c8a4500139e198f/125516c66e82c728ace21e0d46eb9b94378380bdb0fdb151ad4eb2d86b56357c2301a03f32dfa17dbc132a56560c49f8105f0e4cf5f98823f0b33d72825959ffcd7f1d2598694ef1e1c84afd13b0328a468fb7b98e45c2e03523e08a86463b0c48.png)

**Comment by jwhaney** [comment]
can we test the outside entity form without sending an email to the entity? or should we just do it...?

**Comment by adambreznicky** [comment]
thanks for QC'ing the form.

we should test the outside entity form. the way i think we can test it is to create a new, fake outside entity using one of our emails and run the form to send it to ourselves. i'll test this now

**Comment by adambreznicky** [comment]
testing outside entity form sent the proper email to me. this all seems to be working again. closing the issue
