### ISSUE TITLE
WMS and External Entity Catergories Disappeared

### ISSUE THREAD

**Issue by ghost** [TNRIS/data.tnris.org#57]
![image](https://user-images.githubusercontent.com/8459928/214089980-a00f32fc-f911-4ba2-8ac5-c1e258f115d3.png)
![image](https://user-images.githubusercontent.com/8459928/214090040-6933ee2b-b805-48dd-ba36-431b2bf46d63.png)

No ideas on what happened.

**Comment by L-Har** [comment]
This is fixed now
