### ISSUE TITLE
New metadata file needed for Pecos Dallas Hypsography

### ISSUE THREAD

**Issue by birdladyellen** [TNRIS/data.tnris.org#58]
@csidenblad Please update the metadata file for the Pecos Dallas hypsography dataset. Current PDF is unreadable. Below is PDF to use.
[usgs2019-metadata-contours.pdf](https://github.com/TNRIS/data.tnris.org/files/10943464/usgs2019-metadata-contours.pdf)

**Comment by birdladyellen** [comment]
Please update Metadata file on N:\data

**Comment by csidenblad** [comment]
@birdladyellen I have looked into the corrupt PDF and have found another collection (USGS 2019 Desert Mtns) that also appears to be corrupt. Could you look into other previous collections so we can figure out which collections need updated metadata? You can check with @ThorTheDestroyer on which collections might need to be researched.

**Comment by csidenblad** [comment]
@ThorTheDestroyer I also noticed that the updated metadata pdf lists the spatial ref as Web Mercator. Is this correct? Do the contours not get reprojected to original projection after being created?

**Comment by ThorTheDestroyer** [comment]
@csidenblad yeah,  I always create them in their native projection so I was surprised as well that this was in the google WGS 84. I think this is the only one with that projection, so I'll see about reprojectioning it.

**Comment by birdladyellen** [comment]
@csidenblad Attached are the updated pdf/txt files for the 2019 USGS Desert Mountain collection

[usgs19-desert-mountains-metadata-contours.txt](https://github.com/TNRIS/data.tnris.org/files/10981918/usgs19-desert-mountains-metadata-contours.txt)
[usgs19-desert-mountains-metadata-contours.pdf](https://github.com/TNRIS/data.tnris.org/files/10981919/usgs19-desert-mountains-metadata-contours.pdf)

**Comment by csidenblad** [comment]
@ThorTheDestroyer @birdladyellen 
Is there a way to export the .xml or .shp.xml to export with future contours so we no longer need the pdf metadata file to be included in the zips?

**Comment by ThorTheDestroyer** [comment]
@csidenblad If GIT has any ideas on how to achieve this easily at the file level instead of product level, I'd have not issue implementing it.  I currently don't see a justification for the value add vs amount of work to create GDB out of them, adding the metadata then re-exporting and tiling them back to individual shapefiles. 

I'll will look through Global Mapper and see if there are any options when we originally convert them to .shps.
