### ISSUE TITLE
Collection Missing from Front End

### ISSUE THREAD

**Issue by ThorTheDestroyer** [TNRIS/data.tnris.org#59]
@ctrepka @L-Har The collection https://data.tnris.org/collection?c=af8fc6c9-3d3a-4a55-b08d-697d4d4dadb7#9.26/26.4386/-97.375  is missing from the front end of data.tnris.org.  It exists when pathed directly to, and is listed as public in the api.

**Comment by L-Har** [comment]
@ThorTheDestroyer this has been resolved
