### ISSUE TITLE
tool drawer icon badge/indicator

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/data.tnris.org#63]
create an indicator badge for the tool drawer icon which appears while any of the tool drawer filters/sorters are applied. some ideas include a counter of the filters applied (this may not be intuitive) or a subscript exclamation point icon

**Comment by jwhaney** [comment]
exclamation for badge notification when tool drawer closed and filters on. no counter as of now. commit afc18a6f6b3339fc8816ce12a960996e11dfb5cb.

may need to discuss if we want similar or different notification next to list item filters in tool drawer when open.

**Comment by jwhaney** [comment]
resolved buggy tool drawer notification issue with commit 119e30284c5899c1fa847422f8c54bc2ba8f73db; merged and finalized with commit 87c395bd687f11ab22cf6b8dad2e44d5f7bc72eb
