### ISSUE TITLE
carousel max size

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/data.tnris.org#67]
update carousel style height limit for consistency regardless of image size. take into account that all photos will be a standard size in the future, this is a preventative measure to control when bad images are uploaded by accident (and the current legacy images while they are updated)

**Comment by jwhaney** [comment]
resolved via commit c68b2701634bcd1ecc7b465e3e03e37e4e1e3fc9

**Comment by jwhaney** [comment]
new resolution with commit 1a7f81e990815085b9cc6af9e9fe6fd4dfd896a9
