### ISSUE TITLE
Recreate Adjacent States Image

### ISSUE THREAD

**Issue by christoball** [TNRIS/data.tnris.org#79]
- Needs basic aerial imagery underneath
- Adjacent states imposed on top

**Comment by christoball** [comment]
Specs:
2000x1125px
72dpi

**Comment by christoball** [comment]
Correction, please export at 300dpi so it's available for other uses.

**Comment by e00o** [comment]
Added four versions of the image to - M:\Website\erik_remakes_datacatalog - for your consideration.

**Comment by christoball** [comment]
Image has been remade and uploaded to vault. Resolved!
