### ISSUE TITLE
esri services links

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/data.tnris.org#84]
update the lambda function which scraps for esri open data portal links to create/grab the link to the open data portal site page for that dataset instead of the service information page.

example:
currently - http://services.arcgis.com/KTcxiTD9dsQw4r7Z/arcgis/rest/services/Texas_Airports/FeatureServer
change to - http://gis-txdot.opendata.arcgis.com/datasets/texas-airports

**Comment by adambreznicky** [comment]
- [ ] as per the hallway discussion, maybe test out disabling all the listed services as links. maybe make the into sentence with the number of services a button which dropdowns a display of all the services listed.

- [ ] test max height of description which hides overflow content and has functionality to expand when user clicks button, ampersand, fade, or something of the like

- [ ] test using the wiki api to be the descriptions

**Comment by jwhaney** [comment]
pull commit a49e3b60b4a4fa4dba8158f69777a0d5c4f5d024 and see what you think. i'll stick this under review.

**Comment by jwhaney** [comment]
commit 6f44c6ad0539151c87403da2b4dd148d2685e6ec

**Comment by jwhaney** [comment]
added a collapsed/minimized description if wiki api response + db description equals div greater than 250px (we can change this later). description is expandable and retractable.
commit fe86fe3440a043239682f7e375ebdb0bda9da8b5

wiki api for outside entities should be completed as well.

**Comment by jwhaney** [comment]
closing this issue out now as i think we finished it up friday.
