### ISSUE TITLE
Recreate Address Points Image

### ISSUE THREAD

**Issue by christoball** [TNRIS/data.tnris.org#85]
The address points dataset needs image examples to go with its entry:
https://data.tnris.org/collection/c56ff69b-efe7-46e7-89c7-43e655188382

Img specs are
2000px wide by 1125 high

72dpi

**Comment by ilyannakadich** [comment]
@christoball can you use either of these? 
M:\Website\SM\AddressPoints.eps 
M:\Website\SM\AddressPoints2.eps

**Comment by christoball** [comment]
@ilyannakadich Their content is good but they need to be horizontal, more of a landscape format, and not portrait. The images should be 16:9 aspect ratio. Should I just turn them?

**Comment by ilyannakadich** [comment]
@christoball  I have the .mxd open at my desk.  Can you come by to assist?

**Comment by ilyannakadich** [comment]
@christoball  I replaced both images above.

**Comment by christoball** [comment]
All updated!
