### ISSUE TITLE
LCD: Field help

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/data.tnris.org#9]
add examples for the fields on the collection page https://data.tnris.org/admin/lcd/collection/

**Comment by adambreznicky** [comment]
commit bb1525fec9341f452d6aa6e3c68c69cc62bc5f71
added a bunch of helper text and did some thumbnail management based on images.

helper text for 'source' and 'agency' have not been completed as it spawned a discussion on how to handle these inappropriately labelled metadata. discussed with Stratmap and they leaned on the idea:
source --> "Partners"
agency --> "Source"

thoughts? maybe we should meet on this one

**Comment by adambreznicky** [comment]
commit 72845b0c7156277009b5844fd563c2dbefb8498a completed the source/agency to partners/source migration.
frontend updated to use new fields. old fields and model still exist as the deployed/prod instance is using them. after next deployment, these old fields/model can be deleted.

post deployment to-do:
- [ ] update collection_catalog_records.sql references to source field and agency_type model. lines: 12, 131-134, 164, 180-183. then copy query into pgadmin and run it.
- [ ] update models.py references to source field in collection table and ccr view, the agency_type table/model. lines: 14-66, 788, 836-841, 927-934, 1185-1187, 1254-1266. then run makemigration and ultimately migrate
- [ ] update admin.py referrences to agencytype. lines: 8, 39-43
- [ ] delete agency_type.json from fixtures folder?

...and that should be it. there may be more references but i can't find them.

**Comment by adambreznicky** [comment]
final adjustments completed after redeployment. commit e48423cc1e5afadeee86c3fdc8fd904fb675a729
