### ISSUE TITLE
No spaces between comments on Lookup lists

### ISSUE THREAD

**Issue by christoball** [TNRIS/data.tnris.org#91]
There are currently no spaces between some items displayed in the metadata of datasets.

See image in following comments.

**Comment by christoball** [comment]
This on the Central Texas Lidar Page but the same thing occurs on all datasets
https://data.tnris.org/collection/0549d3ba-3f72-4710-b26c-28c65df9c70d

![nocommas.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599de1581827cf2b06d2e400/125516c66e82c728ace21e0d46e69b992c8f8ea89cabf301b44fff9e2c4533317346f62821d4b471bc157f00580e46a541595712f9f88b23a3e42e6c981e5ab38532022d8c6853beb2901eb60bbb258e4f87b3bf8a44c6ea3f20f5c6.jpg)

**Comment by jwhaney** [comment]
resolved via commit 6b6f6ba9c3e0cb96015359b07b8d3caeee876909
