### ISSUE TITLE
Header for WMS

### ISSUE THREAD

**Issue by christoball** [TNRIS/data.tnris.org#92]
Add a header for the Web Mapping Services on dataset pages.

See example image in following comment.

**Comment by christoball** [comment]
[Uploading wmsheader.jpg...]

**Comment by mitchellryant** [comment]
I always hated the idea that is it refered to as a WMS Service, when S stands for service.  
**WMS Service -> Web Mapping Service Service.** How does this text sound?

Online Mapping Service

This dataset is available as an online mapping service. Use this URL below to connect to the service in your software. To use the service in your software package, consult the software help\support information.

**Comment by jwhaney** [comment]
soooo, just to clarify are you saying that we need to change the service text blurb to what you have there @mitchellryant and also add a header/title that says "Online Mapping Service"?

**Comment by mitchellryant** [comment]
yes

**Comment by jwhaney** [comment]
ok gotchya

**Comment by jwhaney** [comment]
resolved with commit 19032b447145a47b7b837f62323d265a1a4f81aa
