### ISSUE TITLE
Recreate Bathymetry Dataset Image

### ISSUE THREAD

**Issue by christoball** [TNRIS/data.tnris.org#96]
Recreate image and/or images for bathymetry dataset

https://data.tnris.org/collection/8fe992d8-1019-492a-b36b-9cfc3293ac6b

**Comment by e00o** [comment]
Added four versions of the image to - M:\Website\erik_remakes_datacatalog - for your consideration.

**Comment by christoball** [comment]
Image has been remade and uploaded to vault. Resolved!
