### ISSUE TITLE
Return to Area Scrolled to in Catalog

### ISSUE THREAD

**Issue by christoball** [TNRIS/data.tnris.org#99]
When you go to a full dataset, and then return back to the multiple dataset browsing, can it return to where you were scrolled to.

This would replicate the same behavior on Google Fonts, and also return users to where they were already browsing, especially when looking at a large number of datasets.

Currently, it resets the datasets to the top of the window.

**Comment by adambreznicky** [comment]
1. scroll down the catalog grid view
2. open a collection

now you have 2 options:

3A. click the browser "back" arrow, this returns you to the scrolled place on the page

or

3B. click the catalog grid button, this return you to the top of the page

this is the correct functionality (the exact same as google fonts) and the app currently  behaves this way.
